---
title: 'Udvalgte Lovecraft Fortællinger'
Subtitle: > 
    Dansk oversættelse af udvalgte fortællinger af H.P. Lovecraft til dansk. 
author:
- H.P. Lovecraft
keywords: Lovecraft
language: da-DK
tags: [the king in yellow, chambers]
cover-image: images/lovecraft.jpg
lang: da
stylesheet: epub.css
publisher: http://gittobook.org
rights: http://creativecommons.org/licenses/by-sa/2.5/
#date: 1895
# are exports private or not / only repo owner can download exports (epub, mobi)
private: true

# pandoc format arguments
# because of security these options are limited
format-arguments:
    pdf: -V documentclass=memoir template=templates/latex.default -S --toc --chapters -V fontsize=12pt  -V lang=danish
    epub: -S --toc --toc-depth=1
    mobi: ok
    html-chunked: -s -S
# ignore files
ignore-files:
    - README.md
...
